VERSION: 2
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

  META_ARCHITECTURE: "MultiGeneralizedRCNNDetector"

  BACKBONE:
    NAME: "build_timm_bifpn_backbone"

  TIMMNETS:
    NAME: "tf_efficientnetv2_m.in21k"
    PRETRAINED: True
    OUT_FEATURES: (1,2,3,4)
    NORM: "FrozenBN"

  FPN:
    IN_FEATURES: ["s1", "s2", "s3", "s5"]

  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]] # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]] # Three aspect ratios (same for all in feature maps)

  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000 # Per FPN level
    PRE_NMS_TOPK_TEST: 1000 # Per FPN level
    POST_NMS_TOPK_TRAIN: 1500
    POST_NMS_TOPK_TEST: 1000

  DENSEPOSE_ON: True
  KEYPOINT_ON: True

  ROI_HEADS:
    NAME: "DensePoseROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 1

  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
    SMOOTH_L1_BETA: 0.5

  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14

  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseV1ConvXHead"
    POOLER_TYPE: "ROIAlign"
    NUM_COARSE_SEGM_CHANNELS: 2
    CSE:
      EMBEDDERS:
        "smpl_27554":
          TYPE: vertex_feature
          NUM_VERTICES: 27554
          FEATURE_DIM: 256
          FEATURES_TRAINABLE: False
          IS_TRAINABLE: True
          INIT_FILE: "https://dl.fbaipublicfiles.com/densepose/data/cse/lbo/phi_smpl_27554_256.pkl"

  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    IN_FEATURES: ["p6"]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    COMMON_STRIDE: 64
    NUM_CLASSES: 20
    LOSS_TYPE: "hard_pixel_mining"
    USE_DEPTHWISE_SEPARABLE_CONV: True
    IGNORE_VALUE: 0

DATASETS:
  TRAIN:
  - "my_densepose_coco_2014_train_cse"
  TEST:
  - "my_densepose_valminusminival2014_cse"
  CLASS_TO_MESH_NAME_MAPPING:
    "0": "smpl_27554"

SOLVER:
  BASE_LR: 0.00125
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 8
  MAX_ITER: 90000
  WARMUP_FACTOR: 0.1
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0

INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 1536
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: False

DATALOADER:
  NUM_WORKERS: 10

SEED: 9269883
